# Numpy Class

In [1]:
import numpy as np

# Creating Arrays

In [12]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a)) 
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [5]:
# Creating array from list with type float
b = np.array([[1, 2, 4], 
              [5, 8, 7]], 
             dtype = 'float')
b

array([[1., 2., 4.],
       [5., 8., 7.]])

In [13]:
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   

(3,)
1 2 3


In [8]:
print(b.shape)

(2, 3)


In [15]:
a[0] = 5                  # Change an element of the array
print(a)                 

[5 2 3]


In [16]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              

[[0. 0.]
 [0. 0.]]


In [17]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              

[[1. 1.]]


In [19]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               

[[7 7]
 [7 7]]


In [21]:
d = np.eye(3)         # Create a 2x2 identity matrix
print(d)             

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                    

[[0.28607314 0.6079275 ]
 [0.21769247 0.55119816]]


# Indexing

In [23]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
# Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [25]:
# A slice of an array is a view into the same data, so modifying it will modify the original array.
print(a[0, 1])   

b[0, 0] = 77     
print(a[0, 1]) 
b

2
77


array([[77,  3],
       [ 6,  7]])

In [26]:
a = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

# Two ways of accessing the data
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)  

[4 5 6] (3,)
[[4 5 6]] (1, 3)


In [27]:
# Same when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape) 

[2 5 8] (3,)
[[2]
 [5]
 [8]] (3, 1)


In [28]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
x = np.arange(1,7)  #arange(start,stop,step)
x.shape = (3,2)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

# Integer Array indexing

In [30]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [31]:
print(a[[0, 1, 2], [0, 1, 0]])

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [32]:
#One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [33]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9], 
              [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


# Boolean array indexing

In [37]:
a = np.array([[1,2], 
              [3, 4], 
              [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     
print(bool_idx)    

[[False False]
 [ True  True]
 [ True  True]]


In [38]:
# We use boolean array indexing to construct a rank 1 array
print(a[bool_idx])  

[3 4 5 6]


In [39]:
# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]


# Basic Operations

In [40]:
a = np.array([1, 2, 5, 3])

In [41]:
# add 1 to every element
print (a+1)
print()
 
# subtract 3 from each element
print (a-3)
print()
 
# multiply each element by 10
print (a*10)
print()
 
# square each element
print (a**2)
print()
 
# modify existing array
a *= 2
print (a)
print()
 
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print(a.T)

[2 3 6 4]

[-2 -1  2  0]

[10 20 50 30]

[ 1  4 25  9]

[ 2  4 10  6]

[[1 3 9]
 [2 4 6]
 [3 5 0]]


In [42]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
 
# maximum element of array
print (arr.max())
print (arr.max(axis = 1))       #Row-wise maximum
 
# minimum element of array
print (arr.min(axis = 0))       #Column-wise minimum
 
# sum of array elements
print (arr.sum())              
 
# cumulative sum along each row
print (arr.cumsum(axis = 1))

9
[6 7 9]
[1 1 2]
38
[[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [43]:
# Binary operators: These operations apply on array elementwise and a new array is created. 
# You can use all basic arithmetic operators like +, -, /, , etc. 
# In case of +=, -=, *= operators, the exsisting array is modified.

In [44]:
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])
 
# add arrays
print ("Array sum:\n", a + b, "\n")
 
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b, "\n")
 
# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]] 

Array multiplication:
 [[4 6]
 [6 4]] 

Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [46]:
# Universal functions (ufunc): NumPy provides familiar mathematical functions such as sin, cos, exp, etc. 
# These functions also operate elementwise on an array, producing an array as output.
# Note: All the operations we did above using overloaded operators can be done using ufuncs like:
# np.add, np.subtract, np.multiply, np.divide, np.sum, etc.

In [45]:
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values:", np.sin(a), "\n")
 
# exponential values
b = np.array([0, 1, 2, 3])
print ("Exponent:", np.exp(b), "\n")
 
# square root of array values
print ("Square root:", np.sqrt(b))

Sine values: [0.0000000e+00 1.0000000e+00 1.2246468e-16] 

Exponent: [ 1.          2.71828183  7.3890561  20.08553692] 

Square root: [0.         1.         1.41421356 1.73205081]
